### ISSUE TITLE
siar is disfunct

### ISSUE THREAD

**Issue by Niemand112233** [yutakaos/archives#1]
Hi,

you are using the library "siar", which is, however, removed from cran repository. Will you update your code in the future?

**Comment by yutakaos** [comment]
Thanks for contacting me.

I only used "siar" package to load sample data. So, you can install and use "siarbeta" package regardless of "siar" disfunction. I will change the sample data in the future.

**Comment by yutakaos** [comment]
I modified the example code without using the "siar" package.
